# Generated by Django 5.2.4 on 2025-07-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_businessprofile_avatar_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='avatar_picture',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='banner_picture',
        ),
    ]
