# Generated by Django 5.2.4 on 2025-07-19 21:49

import app.models2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_businessprofile_avatar_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='avatar_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.models2.avatar_upload_to),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.models2.banner_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models2.post_image_upload_to),
        ),
    ]
