# Generated by Django 5.2.4 on 2025-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_businessprofile_avatar_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='redeem_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
