# Generated by Django 5.2.4 on 2025-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_discount_redeem_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='redeem_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
