services:
  - type: web
    name: anticrisis-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: anticrisis.settings
      - key: SECRET_KEY
        sync: false  # Render will ask you to set this securely in the dashboard


# services:
#   - type: web
#     name: antcrisis-backend
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: python manage.py runserver 0.0.0.0:$PORT
